[workspace]
members = [".", "screencast"]
#members = [".", "screencast-vr", "screencast"]

[package]
name = "stereokit_rust_gstreamer"
version = "0.1.0"
edition = "2021"
description = "My stereokit VR program"
keywords = ["stereokit", "XR", "VR", "AR", "sys"]
license = "MIT"
repository = "https://github.com/mvvvv/StereoKit-rust-gstreamer"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib"]

[features]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
stereokit-rust = { path = "../StereoKit-rust", features = ["event-loop"] }
# stereokit-rust = { version = "0.4.0-alpha.22", features = ["event-loop"] }
stereokit-macros = { path = "../StereoKit-rust/stereokit-macros" }
winit = { version = "0.30", features = [ "android-native-activity" ] }
anyhow = {version = "1.0"}
gstreamer = {version = "0.25"}
gstreamer-sys = {version = "0.25"}
gstreamer-app = {version = "0.25", features = ["v1_24"]}
gstreamer-audio = {version = "0.25", features = ["v1_16"]}
gstreamer-video = {version = "0.25"}
byte-slice-cast = "1.2"
openxr-sys = "0.13"


[target.'cfg(target_os = "android")'.dependencies]
stereokit-rust = { path = "../StereoKit-rust", features = ["event-loop","build-dynamic-openxr"] }
# stereokit-rust = { version = "0.4.0-alpha.22", features = ["event-loop","build-dynamic-openxr"] }
log = "0.4"
android_logger = "0.15"
ndk-context = "0.1"
ndk = "0.9.0"
ndk-sys = "0.6.0"
jni = "0.22"

 