[package]
name = "screencast-vr"
version = "0.1.0"
authors = ["© mv81 https://github.com/mvvvv"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.79"
publish = false

[dependencies]
serde = "1.0"
eframe = { version = "0.33", features = [
    "default",
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }

zbus = "5.2" # , features-default = false, features = ["tokio"]}
anyhow = { version = "1.0" }
dirs = "6.0"

# For image support:
egui_extras = { version = "0.33", features = ["default", "image"] }
log = {version = "0.4"}
env_logger = { version = "0.11", default-features = false, features = [
    "auto-color",
    "humantime",
] }


tokio = { version = "1.42" , features = [ "full"]}
async-io = { version = "2.4"}
async-std = { version = "1.13", features = ["attributes"]}
futures-util = { version = "0.3" }
gstreamer = {version = "0.24"}
gstreamer-rtsp = {version = "0.24"}
gstreamer-rtsp-server = {version = "0.24"}